## Question: 
Given two matrices, write a program to multiply them.

### Step 1: 
Create a most basic solution. Cheat if you have to. This step is to help us understand the problem better and in more depth. Understandably a lot of problems don't have such easy or quick solutions, in those cases skip to STEP 2 & workout the problem BY HAND. 

In [117]:
# We cheat a little to help us understand better
import numpy as np

# Sample matrix a
a = [
    [0, -1, 2], 
    [4, 11, 2]
]

# Sample matrix b
b = [
    [3, -1], 
    [1, 2],
    [6, 1]
]

# let's print the number of rows and number of columns for each matrix
print (f"Matrix A: {len(a):9} rows x {len(a[0])} cols")
print (f"Matrix B: {len(b):9} rows x {len(b[0])} cols")

# mulitply the matrix using numpy
result = np.array(a) @ np.array(b)

# Shape of resultant array
print (f"\nResultant Matrix: {len(result)} rows x {len(result[0])} cols")

# how does output look?
result

Matrix A:         2 rows x 3 cols
Matrix B:         3 rows x 2 cols

Resultant Matrix: 2 rows x 2 cols


array([[11,  0],
       [35, 20]])

##### `Note` on python f Statements:

Python F statements help us combine python code in between lines of text. It is convenient in a lot of ways plus also supports cool formattings tweaks.

In [119]:
# example of f - statement
f"Hello World{'!' * 10}"

'Hello World!!!!!!!!!!'

From the above multiplication, we can notice that after multiplication the shape of resultant matrix is different from either of the two matrices. We will dig more into it shortly. 

But before that, let's write python functions to replicate the results. We want the function to be such that, given two matrices as inputs, we want it to print the shapes and return the product of two matrices.

In [120]:
def np_mul(a, b):
    
    '''We are basically copy pasting code from above with the exception of `return result`.
    return statements in python basically return a value to the `caller`.
    
    def square(a):
        result = a * a
        return result
        
    a = 10
    b = square(a)
    
    The value of b after the function call now becomes 100. We assign b with whatever value results from 
    the `square` function call.
    
    '''
    
    print (f"Matrix A: {len(a):9} rows x {len(a[0])} cols")
    print (f"Matrix B: {len(b):9} rows x {len(b[0])} cols")
    
    result = np.array(a) @ np.array(b)

    print (f"\nResultant Matrix: {len(result)} rows x {len(result[0])} cols")
    
    return result

`Note` on `split` *method*, `map` *function* and `lambda` *keyword*:

1. split() is a string *method*. If you type in str.\<tab\> it will show you a list of all *methods* available for string *objects*. Everything in the world of python is an object. (for a later tutorial). Split function splits the string based on a given *delimiter* passed as a argument. If you simply do a `str.split()` without any *arguments*, the delimiter is set by default to a whitespace character (tabs, spaces, newlines, etc).

2. map() is one of my favorite functions. It takes in two arguments:
    - function: Can be any function
    - iterable: if you can do a "for i in \<insert_object_here\>" without any error, it is an iterable. Eg: Strings, List, Tuples, etc
    
3. lambda is similar to the "def" keyword of python, in a sense that both help in creating a function. lambda keyword however helps create "short handed" functions. It assumes the following format: `lambda <input(s)>: <output(s)>`. 
    
Now applying what we had learnt in this **Note** section, lets do a simple task: Convert a string of numbers to a integer array.

In [123]:
# our string of numbers
temp = "1 2 3 4"
print (temp)

# let's use the split() method, by default delimiter is one or more whitespace(s)
temp = temp.split()
print (temp)

# first we don't use map(), lets use simply a for loop
for i in range(len(temp)):
    temp[i] = int(temp[i])
    
print (temp)

1 2 3 4
['1', '2', '3', '4']
[1, 2, 3, 4]


Now lets use map functions to do the same:

In [127]:
# map function without lambda
def square(x):
    return x * x

# how does it look?
list(map(square, [1, 2, 3, 4]))

[1, 4, 9, 16]

In [129]:
# map function with lambda
square = lambda x: x * x

# lambda syntax: lambda <inp>: <output>
list(map(square, [1, 2, 3, 4]))

[1, 4, 9, 16]

Due to its extremely convenient notation, it can be used as another argument straight away without the need to saving the function to an *indentifier.* 

See the example below where we convert a string to integer:

In [130]:
# we don't create a new function, rather pass lambda function directly
list(map(lambda x: int(x), ['1', '2', '3', '4']))

[1, 2, 3, 4]

Without you realizing it, you have succesfully learnt how to convert a string of numbers to an integer array. Congradulations!

The above understanding was needed before we proceeded further. Now let's create that function that will input two matrics from the user, i.e, YOU.

In [131]:
def get_matrix():
    
    m = int(input("Enter the number of Rows for Matrix A: "))
    n = int(input("Enter the number of Columns for Matrix A"))

    a = []
    for i in range(m):
        row = input()       # get string input from user '1 2 3 4'
        row = row.split()   # split it into so: ['1', '2', '3', '4']
        row = map(int, row) # use map function to convert string array to int array
        row = list(row)     # map function returns a map object, convert it to list object
        a.append(row)       # append the row to list

    m = int(input("\nEnter the number of Rows for Matrix B: "))
    n = int(input("Enter the number of Columns for Matrix B"))

    b = []
    for i in range(m):
        
        # chaining all the code above into a single line
        b.append(list(map(int, input().split())))
        
    # finally we return (a, b): (Matrix a, Matrix b): (list, list)
    return a, b

In [132]:
# lets check if our function works fine
get_matrix()

Enter the number of Rows for Matrix A:  4
Enter the number of Columns for Matrix A 2
 1 2
 3 4
 5 6
 7 8

Enter the number of Rows for Matrix B:  2
Enter the number of Columns for Matrix B 3
 1 2 3
 4 5 6


([[1, 2], [3, 4], [5, 6], [7, 8]], [[1, 2, 3], [4, 5, 6]])

Working good. Now onto STEP2! 

### Step 2:
In order to solve a programming problem, we need to understand the problem ourselves first. Efficient solutions can only be discovered if YOU have a thorough understanding of the problem. 

Against a set of inputs, workout your solution and compare it with the expected solution. If you don't have the luxury of a working solution yet, by all means work out the problem by HAND.

In the code below, the cell keeps executing untill \<CTRL\> + C is hit. We keep inputing different set of inputs and checking the corresponding outputs. While doing so, do with the intent to discern a pattern of how the problem is actually solved. Your brain is really incredible at doing this. Keep solving sample problems until you have a vague mental algorithm of the how the problem could be solved.

In [135]:
while True:
    try:
        
        a, b = get_matrix()

        print()
        temp = np_mul(a, b)
        print (temp)
        
    except KeyboardInterrupt:
        break
        
    except:
        print ("Invalid Input! Press CTRL + C to exit.\n")

Enter the number of Rows for Matrix A:  a


Invalid Input! Press CTRL + C to exit.


Enter the number of Rows for Matrix A:  2
Enter the number of Columns for Matrix A 3
 1 2 3
 4 5 6

Enter the number of Rows for Matrix B:  1
Enter the number of Columns for Matrix B 3
 1 2 3



Matrix A:         2 rows x 3 cols
Matrix B:         1 rows x 3 cols
Invalid Input! Press CTRL + C to exit.


Enter the number of Rows for Matrix A:  2
Enter the number of Columns for Matrix A 3
 1 2 3
 4 5 6

Enter the number of Rows for Matrix B:  3
Enter the number of Columns for Matrix B 5
 1 2 3 4 5
 1 2 3 4 5
 1 2 3 4 5



Matrix A:         2 rows x 3 cols
Matrix B:         3 rows x 5 cols

Resultant Matrix: 2 rows x 5 cols
[[ 6 12 18 24 30]
 [15 30 45 60 75]]


Enter the number of Rows for Matrix A:  a


### Step 3: 

At this stage, we analyze and workout a rough algorithm. Here are our observations from previous step:

1. Shape of resultant matrix is a combination of shape of matrix A and shape of Matrix B. 

        Let Shape of matrix A => (m1, n1)
        Let shape of matrix B => (m2, n2)
        Then, Shape of resultant Matrix => (m1, n2)
        

2. The value at any point of resultant matrix say (x, y) is the sum of individual products of row x of Matrix A and column y of Matrix B.

For eg: 
```
A = [
    [0, -1, 2], 
    [4, 11, 2]
]

B = [
    [3, -1], 
    [1, 2],
    [6, 1]
]

Let result = A @ B

Then value at any point (x, y): 
    result[x, y] = sum(A[x] * B[:, y])
    
Where B[:, y] implies yth column of matrix B.

result[0, 0] = sum(A[0], B[:, 0])
result[0, 0] = sum([0, ,-1, 2] * [3, 1, 6])
result[0, 0] = sum([0, -1, 12])
result[0, 0] = 11

```

Now let's slowly translate the above logic into running python code! To tinker with again, let's have two sample matrics ready:

In [136]:
# Sample matrix a
a = [
    [0, -1, 2], 
    [4, 11, 2]
]

# Sample matrix b
b = [
    [3, -1], 
    [1, 2],
    [6, 1]
]

`Note` on assert *keyword*:

*assert* keyword helps in placing periodic checks in our code. It is incredibly helpful especially when we build our code in a trial and error fashion. Strategically placing assertion statements can save us a ton of time that would be wasted otherwise in debugging errors.

The syntax is as follows: `assert <condition>`. It is really that simple. It throws an error if the condition is False and if the condition evaluates to True it does nothing and lets the program to proceed. Assertion statements are more like tollgates that ensure the program is proceeding as it should be proceeding.

In [138]:
# # Does nothing
# assert True

# throws an AssertionError
assert False

AssertionError: 

### Step 4:

Let's start building our code piece by piece. We will create several 'versions' of our actual function. Each version being built on top of the previous work that we had tested to be working right.

At the most basic stage, we need to ensure that matrices given as input be of the right shapes. Check what happens when we give 'wrong' shapes to numpy's matrix mulitplication:

In [145]:
# (2, 3) @ (2, 3) is WRONG
np_mul(a, a)

Matrix A:         2 rows x 3 cols
Matrix B:         2 rows x 3 cols


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Hence let's implement the same logic into our function as well:

In [146]:
def multiply(a, b):
    assert len(a[0]) == len(b)

In [148]:
multiply(a, a)

AssertionError: 

Since we would be needing to calculate the matrix shapes frequently, let's write a simple function to help us do that.

In [161]:
def get_size(matrix):
    'Rows -> len(matrix) | Columns -> len(matrix[0])'
    
    # ensure that it is actually a proper matrix
    assert (len(matrix) > 0) and (type(matrix[0]) == list) and (list(map(len, matrix)).count(len(matrix[0])) == len(matrix))
    
    # return (row_size, col_size)
    return len(matrix), len(matrix[0])

In [166]:
# should work as expected
print ("Rows, Columns for Matrix A:", get_size(a))

# should throw an error
get_size([[1, 2, 3], [1, 2]])

Rows, Columns for Matrix A: (2, 3)


AssertionError: 

Now let's alter our multiply function such that it can return an empty list of the proper size of resultant matrix. We will write the logic to fill in those values at a later stage.

In [234]:
def multiply(a, b):
    
    # obtain the size of matrix a and matrix b
    size1 = get_size(a)
    size2 = get_size(b)
    
    # ensure the size compatibility
    assert size1[1] == size2[0]
    
    # how should the resultant matrix be shaped?
    size3 = (size1[0], size2[1])
    
    # each row should have the following shape: [0, 0, ... size2[1] / size3[1]]
    # there should be size1[0] number of such rows
    # this Format is called as List Comprehension where condense two for loops
    
    result = [
        [0 for i in range(size3[1])]   # Inner Loop, each row
              for i in range(size3[0]) # Outer loop
    ]
    
    return result    

Let's test our code until this step.

In [235]:
print ("Shape of A:", get_size(a))
print ("Shape o B:", get_size(b))
print ("Shape of Result:", get_size(multiply(a, b)))

print ("\nShape of A:", get_size(b))
print ("Shape o B:", get_size(a))
print ("Shape of Result:", get_size(multiply(b, a)))

Shape of A: (2, 3)
Shape o B: (3, 2)
Shape of Result: (2, 2)

Shape of A: (3, 2)
Shape o B: (2, 3)
Shape of Result: (3, 3)


Working good! Now we have arrived at the climax of our notebook. This is the most crucial part where we are going to implement the second insight from **STEP 2**.

I always believe that if any step can be broken down into simpler steps, always do so. We can later integrate these tinier subfunctions. I love this approach since if we eliminate the possibility of error in the subfunction and the result is still not as the one we expected, we pin point the error to the integration portion of the code and not the subfunction itself.

Soo let's work that portion out:

In [236]:
def multiply_elements(a, b):
    '''
    Given two lists we need a function that will multiply the individual elements and return a list.
    
        Input  => [1, 2, 3], [2, 2, 2]
        Output => [2, 4, 6]
    '''
    
    # firstly ensure that both lists are of same shape
    assert len(a) == len(b)
    
    result = []
    for i in range(len(a)):        # len(a) == len(b) so can insert anything here
        result.append(a[i] * b[i]) # multiply result and add it to the list
        
    return result

In [237]:
# now let's test our little function against different inputs

print (multiply_elements([1, 2, 3, 4], [2, 2, 2, 2]))
print (multiply_elements([1, 2, 3], [2, 2, 2]))
print (multiply_elements([1, 2], [3, 4]))
print (multiply_elements([1], [100]))

# should throw an error
multiply_elements([1, 2,], [1])

[2, 4, 6, 8]
[2, 4, 6]
[3, 8]
[100]


AssertionError: 

Now we write another function that would help us get all the elements of a matrix "column wise".

In [238]:
def get_col_by_index(matrix, index):
    
    # obtain the dimensions of the matrix
    m, n = get_size(matrix)
    
    # ensure that the index lies within the dimensions of matrix
    # n is maximum number of columns
    # We use "-1" since indices start with 0 and end at n - 1
    assert 0 <= index <= n - 1 
    
    result = []
    for i in range(m):
        result.append(matrix[i][index])
        
    return result

In [239]:
# verify they match

col = 1
get_col_by_index(b, col), list(np.array(b).T[col])

([-1, 2, 1], [-1, 2, 1])

We now combine `get_col_by_index` and `multiply_elements`. Let's see how that can be done.

In [240]:
# At position (0, 0) of resultant matrix, the value should be
print (f"We multiply {a[0]} with {list(np.array(b).T[0])} element by element.")
temp = multiply_elements(a[0], get_col_by_index(b, 0))

print ("We get result:", temp)
print ("\nResult's Sum:", sum(temp))
print ("Actual Value:", (np.array(a) @ np.array(b))[0, 0])

We multiply [0, -1, 2] with [3, 1, 6] element by element.
We get result: [0, -1, 12]

Result's Sum: 11
Actual Value: 11


Here's where all the code we've built so far, comes together.

In [241]:
def multiply(a, b):
    
    # obtain the size of matrix a and matrix b
    size1 = get_size(a)
    size2 = get_size(b)
    
    # ensure the size compatibility
    assert size1[1] == size2[0]
    
    # how should the resultant matrix be shaped?
    size3 = (size1[0], size2[1])
    
    # each row should have the following shape: [0, 0, ... size2[1] / size3[1]]
    # there should be size1[0] number of such rows
    # this Format is called as List Comprehension where condense two for loops
    
    result = [
        [0 for i in range(size3[1])]   # Inner Loop, each row
              for i in range(size3[0]) # Outer loop
    ]
    
    # we iterate through each and every position of resultant matrix
    # for each position (x, y), we make suitable function call as we did above
    
    for i in range(size3[0]):
        for j in range(size3[1]):
            
            # multiply individual values, sum it all up and save to result[x, y]
            result[i][j] = sum(multiply_elements(a[i], get_col_by_index(b, j)))
            
    return result

### Step 5:

Finally, verify that the outputs of your code matches with the expected output.

In [232]:
np_mul(a, b)

Matrix A:         2 rows x 3 cols
Matrix B:         3 rows x 2 cols

Resultant Matrix: 2 rows x 2 cols


array([[11,  0],
       [35, 20]])

In [233]:
np.array(multiply(a, b))

array([[11,  0],
       [35, 20]])